[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "corepack prepare pnpm@8.15.0 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build --filter=@nexus360/api"]

[start]
cmd = "pnpm --filter=@nexus360/api start"
